language: java
jdk:
  - oraclejdk8
cache:
  directories:
    - "$HOME/.m2"
install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -Ddownload.cache.skip -B -V
script:
  - mvn test failsafe:integration-test failsafe:verify -Pit -B -V