# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8u171-jdk
    working_directory: ~/repo
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          key: launcher-{{ checksum "pom.xml" }}

      - run:
          name: Compile and install artifacts
          command: mvn install -Dmaven.test.skip=true -DfailIfNoTests=false -DskipTests -B -V

      - save_cache:
          paths:
            - ~/.m2
          key: launcher-{{ checksum "pom.xml" }}

      # Set up environment
      - run:
          name: Set up environment
          command: KEYCLOAK=OFFICIAL ECHO_ENV=NO source launcher-env-template.sh
          when: always

      - run:
          name: Update Hosts File
          command: |
            echo 8.43.84.242 devtools-dev.ext.devshift.net | sudo tee -a /etc/hosts
            cat /etc/hosts

      # run tests!
      - run:
          name: Run Integration Tests
          command: mvn -ff test failsafe:integration-test failsafe:verify -Pit -Dsurefire.rerunFailingTestsCount=2 -DfailIfNoTests=false -B -V
          when: always

      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always

      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results/junit