apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: launchers.launcher.fabric8.io
  namespace: launcher
spec:
  group: launcher.fabric8.io
  version: v1beta1
  scope: Namespaced
  names:
    kind: Launcher
    listKind: LauncherList
    plural: launchers
    singular: launcher