kind: Template
apiVersion: template.openshift.io/v1
objects:
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    name: launcher
  spec:
    to:
      kind: Service
      name: launcher-application
      weight: 100
    wildcardPolicy: None
  status: {}

