kind: Template
apiVersion: template.openshift.io/v1
parameters:
- name: LAUNCHER_MISSIONCONTROL_OPENSHIFT_TOKEN
  displayName: OpenShift token
  description: OpenShift token (leave empty when using Keycloak with OpenShift as an Identity Provider or user/password above)
  value:
- name: LAUNCHER_OAUTH_OPENSHIFT_CLIENT_ID
  displayName: OpenShift Client ID
  description:  The OpenShift Oauth Client ID to use for cluster authentication
  value: launcher
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    name: launcher
  stringData:
    launcher.missioncontrol.openshift.clusters.subscription.token:
    launcher.missioncontrol.openshift.token: ${LAUNCHER_MISSIONCONTROL_OPENSHIFT_TOKEN}
- apiVersion: v1
  kind: Secret
  metadata:
    name: launcher-oauth-openshift
  stringData:
    clientId: ${LAUNCHER_OAUTH_OPENSHIFT_CLIENT_ID}